networks:
  app-network:
    driver: bridge

services:
  petclinic-app:
    image: asia-docker.pkg.dev/spring-petclinic-439415/petclinic/petclinic:%APP_TAG%
    labels:
      service: petclinic
    logging:
      driver: gcplogs
      options:
        labels: "service"
    environment:
      - POSTGRES_URL=%POSTGRES_URL%
      - POSTGRES_USER=%POSTGRES_USER%
      - POSTGRES_PASSWORD=%POSTGRES_PASSWORD%
      - POSTGRES_DB=%POSTGRES_DB%
    networks:
      app-network:
        aliases:
          - petclinic-app
  nginx:
    container_name: nginx
    image: nginx:1.27.2-perl
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      service: nginx
    logging:
      driver: gcplogs
      options:
        labels: "service"
    networks:
      app-network:
